"""empty message

Revision ID: 74d039b1ea87
Revises: 64ed115bbb3f
Create Date: 2021-09-12 00:22:35.817442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d039b1ea87'
down_revision = '64ed115bbb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('padrao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piloto', sa.Integer(), nullable=True),
    sa.Column('rico', sa.Integer(), nullable=True),
    sa.Column('pobre', sa.Integer(), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('pesobrita', sa.Integer(), nullable=True),
    sa.Column('slump', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('piloto'),
    sa.UniqueConstraint('pobre'),
    sa.UniqueConstraint('rico')
    )
    op.create_table('parametros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfa', sa.Integer(), nullable=True),
    sa.Column('c_unitario', sa.Integer(), nullable=True),
    sa.Column('a_unitario', sa.Integer(), nullable=True),
    sa.Column('b_unitario', sa.Integer(), nullable=True),
    sa.Column('c_massa', sa.Integer(), nullable=True),
    sa.Column('a_massa', sa.Integer(), nullable=True),
    sa.Column('b_massa', sa.Integer(), nullable=True),
    sa.Column('c_acr', sa.Integer(), nullable=True),
    sa.Column('a_acr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parametros_alfa'), 'parametros', ['alfa'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parametros_alfa'), table_name='parametros')
    op.drop_table('parametros')
    op.drop_table('padrao')
    # ### end Alembic commands ###
