"""empty message

Revision ID: 960ad287dfd5
Revises: 1928bfc341ed
Create Date: 2021-09-11 23:31:36.298937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960ad287dfd5'
down_revision = '1928bfc341ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parametros', 'b_acr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parametros', sa.Column('b_acr', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
