"""dosagem table

Revision ID: c1ceecd4f284
Revises: 
Create Date: 2021-09-07 14:59:32.450841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ceecd4f284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfa', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parametros_alfa'), 'parametros', ['alfa'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parametros_alfa'), table_name='parametros')
    op.drop_table('parametros')
    # ### end Alembic commands ###
