"""'AdicioneiAgua'

Revision ID: f19f3ddcb72e
Revises: 74d039b1ea87
Create Date: 2021-09-19 14:01:36.508902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19f3ddcb72e'
down_revision = '74d039b1ea87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parametros', sa.Column('agua', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parametros', 'agua')
    # ### end Alembic commands ###
